global:
  scrape_interval:     15s 
  external_labels:
    provider: demodata-google-prometheus-agent        
remote_write:
    - url: "http://10.128.1.22:9090/api/v1/write"

scrape_configs:
  - job_name: 'snmp'
    static_configs:
      - targets: ['10.128.1.23']  # SNMP device.
    metrics_path: /snmp
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.128.1.22:9116
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['10.128.1.23:9100']