version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.33.1
    container_name: prometheus-agent
    hostname: prometheus-agent
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./config.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--enable-feature=agent'
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    ports:
      - "80:9090"